#!/usr/bin/env node
/**
 * Orchelio — code map generator.
 *
 * Writes docs/CODEMAP.md: every source module, its exported symbols, and the
 * first line of its file-level comment.
 *
 * ## Why this exists alongside Graphify
 *
 * Graphify builds a knowledge graph and answers questions about it — better for
 * "how does X reach Y". This produces a flat, deterministic index — better for
 * "where does X live" and "what does this module export". They complement each
 * other, and this one has two properties Graphify does not:
 *
 *   * it needs no API key and no network, so it always works;
 *   * it covers prisma/schema.prisma and the docs, which Graphify's AST pass
 *     skips for want of a grammar.
 *
 * The point of both is the same: an agent that reads one 400-line map instead
 * of grepping eighty files spends a fraction of the tokens and starts from the
 * whole picture rather than a keyword match.
 */

import { existsSync, readFileSync, writeFileSync, readdirSync, statSync } from "node:fs";
import { join, relative, sep } from "node:path";

const ROOT = process.cwd();
const SOURCE_ROOTS = ["src", "prisma", "tests", "scripts"];
const SKIP_DIRECTORIES = new Set(["node_modules", ".next", "generated", "graphify-out", "migrations"]);
const SOURCE_EXTENSIONS = [".ts", ".tsx", ".mjs", ".prisma"];

/** Walks a directory, skipping generated and vendored trees. */
function walk(directory, found = []) {
  let entries;
  try {
    entries = readdirSync(directory);
  } catch {
    return found;
  }

  for (const entry of entries.sort()) {
    if (entry.startsWith(".")) continue;
    const path = join(directory, entry);
    if (statSync(path).isDirectory()) {
      if (!SKIP_DIRECTORIES.has(entry)) walk(path, found);
    } else if (SOURCE_EXTENSIONS.some((extension) => entry.endsWith(extension))) {
      found.push(path);
    }
  }
  return found;
}

/**
 * The first sentence of a file's leading block comment.
 *
 * Every module in this codebase opens with one explaining what it is for; that
 * sentence is the most useful single line about the file, so it is what the map
 * carries.
 */
function purposeOf(source) {
  // The file-level comment sits after the imports, not at byte zero, so look
  // through the opening of the file rather than only at its very start.
  const head = source.split("\n").slice(0, 60).join("\n");
  const match = head.match(/\/\*\*([\s\S]*?)\*\//);
  if (!match) return "";

  const body = match[1]
    .split("\n")
    .map((line) => line.replace(/^\s*\*\s?/, "").trim())
    .filter(Boolean);

  // Skip the "Orchelio — title" line and take the first real sentence.
  const prose = body.filter((line) => !/^Orchelio\s+[—-]/.test(line)).join(" ");
  const sentence = prose.split(/(?<=\.)\s/)[0] ?? "";
  return sentence.length > 170 ? `${sentence.slice(0, 167)}…` : sentence;
}

/** Exported symbol names, in declaration order. */
function exportsOf(source) {
  const names = [];
  const patterns = [
    /export\s+(?:async\s+)?function\s+([A-Za-z0-9_]+)/g,
    /export\s+(?:const|let|class)\s+([A-Za-z0-9_]+)/g,
    /export\s+type\s+([A-Za-z0-9_]+)/g,
    /export\s+default\s+(?:async\s+)?function\s+([A-Za-z0-9_]+)/g,
  ];

  for (const pattern of patterns) {
    for (const match of source.matchAll(pattern)) {
      if (!names.includes(match[1])) names.push(match[1]);
    }
  }
  return names;
}

/** Prisma models, for the schema file. */
function modelsOf(source) {
  return [...source.matchAll(/^model\s+([A-Za-z0-9_]+)\s*\{/gm)].map((match) => match[1]);
}

const files = SOURCE_ROOTS.flatMap((directory) => walk(join(ROOT, directory)));

const grouped = new Map();
for (const path of files) {
  const relativePath = relative(ROOT, path).split(sep).join("/");
  const segments = relativePath.split("/");
  // Group by directory, not by file: `prisma/seed.ts` belongs under `prisma`,
  // not under a group of its own.
  const group = segments.length > 2 ? segments.slice(0, 2).join("/") : segments[0];
  const list = grouped.get(group) ?? [];
  list.push({ path: relativePath, source: readFileSync(path, "utf8") });
  grouped.set(group, list);
}

const lines = [
  "---",
  "title: Code map",
  "tags: [reference, generated]",
  "---",
  "",
  "# Orchelio — Code map",
  "",
  "> Generated by `npm run codemap`. Do not edit by hand.",
  "",
  "Every source module, what it is for, and what it exports. Read this before",
  "searching the codebase: it is one file instead of eighty, and it starts from the",
  "whole picture rather than a keyword match.",
  "",
  "For questions about how modules *reach* each other — call paths, hubs, unexpected",
  "coupling — use the knowledge graph instead: `npm run graph:explain -- \"someSymbol\"`.",
  "See `docs/HARNESS.md`.",
  "",
  `Modules: ${files.length}.`,
  "",
];

for (const [group, entries] of [...grouped.entries()].sort()) {
  lines.push(`## \`${group}/\``, "");

  for (const { path, source } of entries) {
    const purpose = purposeOf(source);
    const symbols = path.endsWith(".prisma") ? modelsOf(source) : exportsOf(source);

    lines.push(`### \`${path}\``);
    if (purpose) lines.push("", purpose);
    if (symbols.length > 0) {
      const label = path.endsWith(".prisma") ? "Models" : "Exports";
      lines.push("", `${label}: ${symbols.map((name) => `\`${name}\``).join(", ")}`);
    }
    lines.push("");
  }
}

const target = join(ROOT, "docs", "CODEMAP.md");
const contents = `${lines.join("\n").trimEnd()}\n`;

/**
 * `--check` writes nothing and reports whether the committed map still matches
 * the source.
 *
 * Comparing content rather than timestamps is the point: a fresh `git clone`
 * gives every file the same modification time, so a mtime comparison calls a
 * perfectly current map stale. Content cannot lie about that.
 */
if (process.argv.includes("--check")) {
  const current = existsSync(target) ? readFileSync(target, "utf8") : "";
  if (current === contents) {
    console.log(`docs/CODEMAP.md is up to date — ${files.length} modules.`);
    process.exit(0);
  }
  console.error("docs/CODEMAP.md is stale. Run `npm run codemap` and commit the result.");
  process.exit(1);
}

writeFileSync(target, contents);
console.log(`docs/CODEMAP.md written — ${files.length} modules indexed.`);
